### ISSUE TITLE
Document security assumptions 

### ISSUE THREAD

**Issue by chris-wood** [tlswg/external-psk-design-team#2]
... and describe attacks in all-honest (general) model. 

<img width="616" alt="Screen Shot 2020-02-21 at 3 32 05 PM" src="https://user-images.githubusercontent.com/2172048/75079931-59c83080-54bf-11ea-8124-58e1460ef121.png">

**Comment by chris-wood** [comment]
@jhoyla can you take this?

**Comment by jhoyla** [comment]
# Attacks on Properties under shared PSKs

TLS 1.3 tries to maintain 8 security properties in the handshake.
A naïve sharing of PSKs, even assuming only honest but curious participants know the key, can violate these properties.

## Establishing the same session keys
Let the group of peers who know the key be A, B, and C.

1. Let the attacker compromise C.
2. A sends a `ClientHello` to  B. 
3. The attacker intercepts it, and passes it to C. 
4. C, under the direction of the attacker, sends a `ClientHello` to B, acting as A. 
5. B responds C thinking he is responding to A.
6. C responds to A.
7. A completes the handshake ostensibly with B, sending a `Finished` message.
8. C sends a `Finished` message to B.
9. B completes the handshake ostensibly with A.  

Although neither A nor B has been compromised, both have completed a session, ostensibly with each other, but have established different keys. 

## Secrecy of Session Keys
Let the group of peers who know the key be A, B, and C. 

1. Let A complete a PSK handshake with B without performing a fresh DHE.
2. C, an honest but curious agent, knows the PSK and can derive the session key.  

## Peer authentication
Let the group of peers who know the key be A, B, and C.

1. A sends a `ClientHello` to B.
2. The attacker redirects the message to C. 
3. C responds to A.
4. A completes the handshake ostensibly with B, sending a `Finished` message. 
5. The attacker redirects the `Finished` message to C.
6. C completes the handshake ostensibly with A. 

## Uniqueness of session keys
Let the group of peers who know the key be A, B, and C.

1. Let the attacker compromise C.
2. A sends a `ClientHello` with no key share to C.
3. The attacker repeats the `ClientHello` to B.
4. B responds to C.
5. The attacker repeats the response to A.
6. A completes the handshake ostensibly with C, sending a `Finished` message.
7. The attacker repeats the `Finished` message to B.
8. B completes the handshake ostensibly with C.

Although neither A nor B has been compromised they have each established a session with the attacker with the same key.

## Downgrade Protection
Let the group of peers who know the key be A, B, and C.
Let A and B support strong and weak cipher suites, but let C support only weaker cipher suites. 

1. A sends a `ClientHello` to B.
2. The attacker redirects the message to C. 
3. C responds to A choosing a weak cipher suite.
4. A completes the handshake ostensibly with B, sending a `Finished` message with a weak cipher suite. 
5. The attacker redirects the `Finished` message to C.
6. C completes the handshake ostensibly with A. 


## Forward secret with respect to long-term keys
Let the group of peers who know the key be A, B, and C.

1. Let A establish a PSK session with B, without a fresh DHE. 
2. Let the attacker record the session.
3. Let the attacker compromise C. 
 
The attacker can decrypt the recorded session, even though she compromised C _after_ A and B completed their session. 

## Key Compromise Impersonation (KCI) resistance
Let the group of peers who know the key be A, B, and C.

1. Let the attacker compromise A.
2. A sends a `ClientHello` to B.
3. The attacker intercepts the `ClientHello` and responds using the PSK learned from A.
4. A completes the handshake ostensibly with B, sending a `Finished` message.

Although B was never compromised the attacker is able to impersonate B to A. 


## Protection of endpoint identities
Although this has not seen any analysis, this appears to be secure, because even honest entities cannot distinguish each other.

**Comment by chris-wood** [comment]
Fixed in #10.
