### ISSUE TITLE
Why do all IoT clients on a system need the same PSK?

### ISSUE THREAD

**Issue by cbartle891** [tlswg/external-psk-design-team#45]
(This question is copied from my email.)

The draft states: "In this use-case, resource-constrained IoT devices act as TLS clients and share the same PSK. The devices use this PSK for quickly establishing connections with a central server. Such a scheme ensures that the client IoT devices are legitimate members of the system."

If the IoT devices only talk to a central server and not each other, why do they all need the same PSK? That doesn't seem like a good idea, given that the clients can then impersonate each other and listen in on each other's traffic.

**Comment by chris-wood** [comment]
@ms-s can you please take this?

**Comment by cbartle891** [comment]
The explanation in https://github.com/tlswg/external-psk-design-team/issues/44 doesn't address why it's okay or desirable for all the clients to have the same PSK. The clients are constrained, being IoT devices, but the server isn't, and presumably can handle n PSKs for n clients.

**Comment by jhoyla** [comment]
The best argument I can come up with for why a server might want all devices to have the same key is if there are many devices and a high rate of turnover. Rather than trying to keep track of rapidly changing list of keys, perhaps it is easier to just use a single key, especially if there is a high penalty if a device is unable to connect.
Further, if the devices have a way of upgrading to a more secure connection when necessary, then the central server may not care if devices can impersonate one another.
Not sure it's very convincing, but perhaps at least plausible?

**Comment by chris-wood** [comment]
I don't think we need to rationalize the use case. The point of this section is to *document* known use cases, not *justify* them, and to provide recommendations for using PSKs in such circumstances. 

@cbartle891: I'm not sure what action you're looking for here. Justification is out of scope, I think.

**Comment by cbartle891** [comment]
You can close this then, since this relates to the discussion elsewhere about justification.
