### ISSUE TITLE
Collisions in PSK identities

### ISSUE THREAD

**Issue by martinthomson** [tlswg/external-psk-design-team#74]
So the draft talks about collisions between PSK identities, with some assumptions baked in:

1. external and resumption PSK identities are trivial to keep distinct (it takes a single bit), but the draft assumes that this step is not taken
2. it might be necessary to generate PSK identities without any sort of centralized coordination, which means that you might need to worry about collisions, but that's another unstated assumption

That first one is pretty poor.

**Comment by russhousley** [comment]
It seems to me that we need to warn implementers about the situation if external and resumption PSKs are not kept distinct.  We could include advice to keep them separate.

**Comment by russhousley** [comment]
I suggest the addition of a paragraph at the end of the Section on "PSK Identity Collisions".

Since resumption PSK identity is assigned by the TLS stack implementation,
it is RECOMMENDED that these identifiers be assigned in a manner that lets
resumption PSKs be distinguished from external PSKs to avoid concerns with
collisions altogether.
